/**
 * 相互運用テストベクタの生成器。
 *
 * TypeScript (ブラウザ) と Rust (aether-cache) は同じ暗号プリミティブを
 * 独立に実装しているため、どこか 1 箇所でもバイト列の組み方がずれると
 *   - 片方が作ったパケットをもう片方が「PoW 不正」として全部捨てる
 *   - peerId から計算するリング座標が食い違い、DHT の担当がずれる
 * といった形で、テストでは気付きにくい壊れ方をする。
 *
 * ここで TS 側の出力を固定ベクタとして書き出し、Rust 側の
 * `tests/interop_vectors.rs` がそれと突き合わせる。
 *
 *   npx tsx tests/vectors/generate.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sodium from 'libsodium-wrappers-sumo';
import {
  powPreimage,
  powHash,
  derivePacketId,
  solvePow,
  type PowCommittedHeader,
} from '../../src/lib/crypto/PowPolicy';
import { NodeIdentity, NODE_ID_POW_FAST } from '../../src/lib/crypto/NodeIdentity';
import { WireCodec } from '../../src/lib/network/wire/WireCodec';
import { WireType } from '../../src/lib/network/wire/WireTypes';
import { JsonBinary } from '../../src/lib/common/JsonBinary';

async function main() {
  await sodium.ready;

  const header: PowCommittedHeader = {
    timestamp: 1_700_000_000_000,
    zone_id: 7,
    pow_difficulty: 8,
    nonce: Uint8Array.from({ length: 12 }, (_, i) => i + 1),
    payload: Uint8Array.from({ length: 40 }, (_, i) => (i * 7) & 0xff),
  };

  const preimage = powPreimage(header);
  const solved = solvePow(header)!;

  // 決定的な鍵ペア (seed 固定) を使う
  const seed = new Uint8Array(32).fill(0x11);
  const kp = sodium.crypto_sign_seed_keypair(seed);
  const peerId = NodeIdentity.derivePeerId(kp.publicKey);

  const challenge = Uint8Array.from({ length: 32 }, (_, i) => (i * 3) & 0xff);
  const signature = sodium.crypto_sign_detached(
    new Uint8Array([
      ...new TextEncoder().encode('AETHER/v3/join'),
      ...challenge,
    ]),
    kp.privateKey,
  );

  const nodePowParams = NODE_ID_POW_FAST;
  const nodePowCounter = NodeIdentity.solveNodeIdPow(kp.publicKey, nodePowParams);

  // ワイヤ検証用の完全な GossipPacket
  const gossipPacket = {
    packet_id: derivePacketId(header),
    hop_count: 3,
    pow_nonce: Number(solved),
    pow_difficulty: header.pow_difficulty,
    timestamp: header.timestamp,
    zone_id: header.zone_id,
    nonce: header.nonce,
    payload: header.payload,
  };
  const mailboxEntry = new TextEncoder().encode(JsonBinary.stringify(gossipPacket));

  const vectors = {
    _comment:
      'Generated by web/tests/vectors/generate.ts — do not edit by hand. ' +
      'Rust (aether-cache/tests/interop_vectors.rs) must reproduce every value.',
    gossipPow: {
      header: {
        timestamp: header.timestamp,
        zone_id: header.zone_id,
        pow_difficulty: header.pow_difficulty,
        nonce: sodium.to_hex(header.nonce),
        payload: sodium.to_hex(header.payload),
      },
      preimage: sodium.to_hex(preimage),
      packetId: derivePacketId(header),
      powHashAtNonce0: sodium.to_hex(powHash(preimage, 0n)),
      solvedNonce: Number(solved),
      powHashAtSolvedNonce: sodium.to_hex(powHash(preimage, solved)),
    },
    boundIdentity: {
      seed: sodium.to_hex(seed),
      pubkey: sodium.to_hex(kp.publicKey),
      peerId,
      position: NodeIdentity.derivePosition(peerId),
    },
    nodeIdPow: {
      params: nodePowParams,
      counter: nodePowCounter,
      hashAtCounter0: sodium.to_hex(
        NodeIdentity.nodeIdPowHash(kp.publicKey, 0, nodePowParams),
      ),
      hashAtSolvedCounter: sodium.to_hex(
        NodeIdentity.nodeIdPowHash(kp.publicKey, nodePowCounter, nodePowParams),
      ),
    },
    joinSignature: {
      domain: 'AETHER/v3/join',
      challenge: sodium.to_hex(challenge),
      signature: sodium.to_hex(signature),
    },

    // ── ワイヤ符号化 ──
    //
    // ここが抜けていたために、JsonBytes が MsgPack の bin 型を読めず
    // 「バイト列を含むメッセージが Rust 側で 1 通も復号できない」という
    // 不具合を長期間見逃していた。暗号プリミティブが一致していても、
    // フレームが解けなければ何も動かない。
    wire: {
      tsFrames: {
        ping: sodium.to_hex(WireCodec.encode(WireType.PING, { ts: 1_700_000_000_000 })),
        hello: sodium.to_hex(WireCodec.encode(WireType.HELLO, { challenge })),
        join: sodium.to_hex(
          WireCodec.encode(WireType.JOIN, {
            peerId,
            pubkey: kp.publicKey,
            powCounter: nodePowCounter,
            challenge,
            signature,
          }),
        ),
        gossip: sodium.to_hex(WireCodec.encode(WireType.GOSSIP, { packet: gossipPacket })),
        // STEM は「TS が送って Rust が読む」方向のテストが無かったため、
        // ワイヤ形式のズレを長期間見逃していた。
        // ★ stemTtl は持たない (発信元を確定させるオラクルになるため廃止)。
        stem: sodium.to_hex(
          WireCodec.encode(WireType.STEM, {
            zoneId: gossipPacket.zone_id,
            packet: gossipPacket,
          }),
        ),
        dhtPut: sodium.to_hex(
          WireCodec.encode(WireType.DHT_PUT, {
            topicHash: 'ab'.repeat(32),
            entries: [mailboxEntry],
          }),
        ),
        pexResponse: sodium.to_hex(
          WireCodec.encode(WireType.PEX_RESPONSE, { peers: [{ id: peerId }] }),
        ),
      },
      /** 期待されるデコード結果 (Rust 側の照合用) */
      expected: {
        pingTs: 1_700_000_000_000,
        challenge: sodium.to_hex(challenge),
        peerId,
        pubkey: sodium.to_hex(kp.publicKey),
        powCounter: nodePowCounter,
        signature: sodium.to_hex(signature),
        gossipPacketId: gossipPacket.packet_id,
        stemZoneId: gossipPacket.zone_id,
        gossipPayload: sodium.to_hex(gossipPacket.payload),
        gossipNonce: sodium.to_hex(gossipPacket.nonce),
        dhtTopicHash: 'ab'.repeat(32),
        /** DHT に保存される形 (JsonBinary 直列化した GossipPacket) */
        dhtEntry: sodium.to_hex(mailboxEntry),
      },
    },
  };

  const out = join(__dirname, 'interop_vectors.json');
  writeFileSync(out, JSON.stringify(vectors, null, 2) + '\n');
  console.log(`wrote ${out}`);
}

main();
